const translations = {
    ru: {
        title: "PhotoBot — Фото на документы",
        login: "🔑 Войти через Telegram",
        auth_code: "Введите код авторизации из бота",
        send: "Отправить",
        auth_info: "👤 Вошли как",
        subscribe_block: "📛 Подпишитесь на нас в Telegram",
        subscribe_ok: "✅ Вы подписаны",
        flux: "🌟 FLUX 2",
        flux_sub: "Black Forest Labs",
        img2img: "🖼️ Изображение в изображение",
        ready_modes: "📋 Готовые режимы",
        documents: "📄 Фото на документы",
        beach: "🌅 Закат на пляже",
        birthday: "🎂👑 День рождения",
        flowers: "🌸 Цветы в авто",
        mirror_male: "🕶️💪 Мужское в зеркале",
        svoboda_f: "🎨 Свободный (ж)",
        svoboda_m: "🎨 Свободный (м)",
        text2img: "📝 Текст в изображение",
        wallpaper: "🖼️ Обои",
        text_models: "💬 Текстовые модели",
        v4flash: "⚡ DeepSeek V4 Flash",
        v4pro: "🧠 DeepSeek V4 Pro",
        phone: "📱 9:16",
        pc: "🖥️ 16:9",
        prompt_placeholder: "Введите промт здесь...",
        hint: "Выберите режим и укажите подпись",
        etalon: "⭐ Использовать эталон",
        generate: "⚡ Сгенерировать",
        prompts: "📋 База промтов",
        storage: "📦 Хранилище генераций",
        agreement: "Пользовательское соглашение",
        privacy: "Политика конфиденциальности",
        chat_title: "💬 PhotoBot",
        chat_subtitle: "общая история с Вашим Ассистентом",
        chat_placeholder: "Задайте вопрос о сервисе",
        chat_input: "Введите сообщение...",
        cookie: "Мы используем необходимые cookie-файлы для авторизации и работы сервиса.",
        cookie_btn: "OK",
        wallpaper_hint: "🖼️ Обои: введите промт",
        documents_hint: "📄 Фото на документы: укажите одежду (например: серая рубашка)",
        beach_hint: "🌅 Закат на пляже: укажите одежду (например: белое платье)",
        birthday_hint: "🎂👑 День рождения: укажите число и цвет платья (например: 23 красное)",
        flowers_hint: "🌸 Цветы в авто: укажите одежду (например: черное платье)",
        mirror_male_hint: "🕶️💪 Мужское в зеркале: опишите одежду, очки, телефон",
        svoboda_hint: "🎨 Свободный (ж): введите промт",
        svoboda_male_hint: "🎨 Свободный (м): введите промт",
    },
    en: {
        title: "PhotoBot — Photo for documents",
        login: "🔑 Log in with Telegram",
        auth_code: "Enter the authorization code from the bot",
        send: "Send",
        auth_info: "👤 Logged in as",
        subscribe_block: "📛 Subscribe to our Telegram",
        subscribe_ok: "✅ You are subscribed",
        flux: "🌟 FLUX 2",
        flux_sub: "Black Forest Labs",
        img2img: "🖼️ Image to Image",
        ready_modes: "📋 Ready Modes",
        documents: "📄 ID Photo",
        beach: "🌅 Beach Sunset",
        birthday: "🎂👑 Birthday",
        flowers: "🌸 Flowers in Car",
        mirror_male: "🕶️💪 Male Mirror Selfie",
        svoboda_f: "🎨 Free (F)",
        svoboda_m: "🎨 Free (M)",
        text2img: "📝 Text to Image",
        wallpaper: "🖼️ Wallpaper",
        text_models: "💬 Text Models",
        v4flash: "⚡ DeepSeek V4 Flash",
        v4pro: "🧠 DeepSeek V4 Pro",
        phone: "📱 9:16",
        pc: "🖥️ 16:9",
        prompt_placeholder: "Enter your prompt here...",
        hint: "Select mode and enter prompt",
        etalon: "⭐ Use Reference",
        generate: "⚡ Generate",
        prompts: "📋 Prompt Library",
        storage: "📦 Generation Storage",
        agreement: "User Agreement",
        privacy: "Privacy Policy",
        chat_title: "💬 PhotoBot",
        chat_subtitle: "shared history with your Assistant",
        chat_placeholder: "Ask a question about the service",
        chat_input: "Type a message...",
        cookie: "We use essential cookies for authorization and service operation.",
        cookie_btn: "OK",
        wallpaper_hint: "🖼️ Wallpaper: enter prompt",
        documents_hint: "📄 ID Photo: specify clothing (e.g., gray shirt)",
        beach_hint: "🌅 Beach Sunset: specify clothing (e.g., white dress)",
        birthday_hint: "🎂👑 Birthday: enter age and dress color (e.g., 23 red)",
        flowers_hint: "🌸 Flowers in Car: specify clothing (e.g., black dress)",
        mirror_male_hint: "🕶️💪 Mirror Selfie: describe clothes, glasses, phone",
        svoboda_hint: "🎨 Free (F): enter prompt",
        svoboda_male_hint: "🎨 Free (M): enter prompt",
    }
};