const translations = {
    ru: {
        title: "PhotoBot — Фото на документы",
        login: "Войти через Telegram",
        auth_code: "Введите код авторизации из бота",
        send: "Отправить",
        auth_info: "Вошли как",
        subscribe_block: "Подпишитесь на нас в Telegram",
        subscribe_ok: "Вы подписаны",
        flux: "FLUX 2",
        flux_sub: "Black Forest Labs",
        flux_info: "FLUX.2 — второе поколение нейросетей для генерации и редактирования изображений от Black Forest Labs. 32 млрд параметров, фотореализм, точная работа с текстом, продвинутое удержание персонажей.",
        img2img: "Изображение в изображение",
        ready_modes: "Готовые режимы",
        documents: "Фото на документы",
        beach: "Закат на пляже",
        birthday: "День рождения",
        flowers: "Цветы в авто",
        mirror_male: "Мужское в зеркале",
        svoboda_f: "Свободный (ж)",
        svoboda_m: "Свободный (м)",
        text2img: "Текст в изображение",
        wallpaper: "Арты, Обои",
        text_models: "Текстовые модели",
        v4flash: "DeepSeek V4 Flash",
        v4pro: "DeepSeek V4 Pro",
        phone: "9:16",
        pc: "16:9",
        prompt_placeholder: "Введите промт здесь...",
        hint: "Выберите режим и укажите подпись",
        etalon: "Использовать эталон",
        generate: "Сгенерировать",
        prompts: "База промтов",
        storage: "Хранилище генераций",
        agreement: "Пользовательское соглашение",
        privacy: "Политика конфиденциальности",
        chat_title: "PhotoBot",
        chat_subtitle: "общая история с Вашим Ассистентом",
        chat_placeholder: "Задайте вопрос о сервисе",
        chat_input: "Введите сообщение...",
        cookie: "Мы используем необходимые cookie-файлы для авторизации и работы сервиса.",
        cookie_btn: "OK",
        wallpaper_hint: "Обои: введите промт",
        documents_hint: "Фото на документы: укажите одежду (например: серая рубашка)",
        beach_hint: "Закат на пляже: укажите одежду (например: белое платье)",
        birthday_hint: "День рождения: укажите число и цвет платья (например: 23 красное)",
        flowers_hint: "Цветы в авто: укажите одежду (например: черное платье)",
        mirror_male_hint: "Мужское в зеркале: опишите одежду, очки, телефон",
        svoboda_hint: "Свободный (ж): введите промт",
        svoboda_male_hint: "Свободный (м): введите промт",
        flash_title: "DeepSeek V4 Flash",
        flash_desc: "Быстрая модель для кода, текстов, повседневных задач. Архитектура Mixture of Experts (236B параметров, 16B активных). Контекстное окно: 1M токенов, вывод до 384K токенов. Поддерживает режим Reasoner. Открытая лицензия MIT.",
        pro_title: "DeepSeek V4 Pro",
        pro_desc: "Флагманская модель для сложных проектов, анализа, больших задач. Архитектура Mixture of Experts (685B параметров, 37B активных). Контекстное окно: 1M токенов, вывод до 384K токенов. Встроенный режим Reasoner. Открытая лицензия MIT.",
        prompts_title: "База промтов",
        prompts_male: "Мужская фотосессия с ИИ",
        prompts_female: "Женская фотосессия с ИИ",
        prompts_kids: "Детская фотосессия (скоро)",
        prompts_anime: "Аниме-образы (скоро)",
        home: "На главную",
        female_title: "Женская фотосессия с ИИ",
        female_subtitle: "10 промтов для создания женских образов",
        female_intro: "Создание профессиональных женских портретов с помощью искусственного интеллекта стало доступно каждому — без фотографа, студии и дорогостоящего оборудования. Современные нейросети генерируют изображения, визуально неотличимые от работы профессионалов, за считанные минуты. Достаточно загрузить своё фото и указать желаемый образ через текстовую инструкцию — промпт.",
        male_title: "Мужская фотосессия с ИИ",
        male_subtitle: "10 промтов для создания мужских образов",
        male_intro: "Создание профессиональных мужских портретов с помощью искусственного интеллекта стало доступно каждому — без фотографа, студии и дорогостоящего оборудования. Современные нейросети генерируют изображения, визуально неотличимые от работы профессионалов, за считанные минуты. Достаточно загрузить своё фото и указать желаемый образ через текстовую инструкцию — промпт.",
        copy: "Скопировать",
        copy_telegram: "Скопировать в Telegram",
        later: "Будет доступно позже",
        back_prompts: "К базе промтов",
        copied: "Скопировано",
        choose_model: "Выберите модель",
        fast: "Fast",
        best: "Best",
        storage_title: "Хранилище генераций",
        loading: "Загрузка...",
        auth_required: "Авторизуйтесь на главной странице",
        empty_storage: "Здесь пока ничего нет",
        loading_prompt: "Загрузка промта...",
        no_prompt: "Без промта",
        delete: "Удалить",
        confirm_delete: "Удалить файл?",
        error_loading: "Ошибка загрузки",
    },
    en: {
        title: "PhotoBot — Photo for documents",
        login: "Log in with Telegram",
        auth_code: "Enter the authorization code from the bot",
        send: "Send",
        auth_info: "Logged in as",
        subscribe_block: "Subscribe to our Telegram",
        subscribe_ok: "You are subscribed",
        flux: "FLUX 2",
        flux_sub: "Black Forest Labs",
        flux_info: "FLUX.2 — second generation neural networks for image generation and editing by Black Forest Labs. 32B parameters, photorealism, precise text rendering, advanced character consistency.",
        img2img: "Image to Image",
        ready_modes: "Ready Modes",
        documents: "ID Photo",
        beach: "Beach Sunset",
        birthday: "Birthday",
        flowers: "Flowers in Car",
        mirror_male: "Male Mirror Selfie",
        svoboda_f: "Free (F)",
        svoboda_m: "Free (M)",
        text2img: "Text to Image",
        wallpaper: "Art, Wallpaper",
        text_models: "Text Models",
        v4flash: "DeepSeek V4 Flash",
        v4pro: "DeepSeek V4 Pro",
        phone: "9:16",
        pc: "16:9",
        prompt_placeholder: "Enter your prompt here...",
        hint: "Select mode and enter prompt",
        etalon: "Use Reference",
        generate: "Generate",
        prompts: "Prompt Library",
        storage: "Generation Storage",
        agreement: "User Agreement",
        privacy: "Privacy Policy",
        chat_title: "PhotoBot",
        chat_subtitle: "shared history with your Assistant",
        chat_placeholder: "Ask a question about the service",
        chat_input: "Type a message...",
        cookie: "We use essential cookies for authorization and service operation.",
        cookie_btn: "OK",
        wallpaper_hint: "Wallpaper: enter prompt",
        documents_hint: "ID Photo: specify clothing (e.g., gray shirt)",
        beach_hint: "Beach Sunset: specify clothing (e.g., white dress)",
        birthday_hint: "Birthday: enter age and dress color (e.g., 23 red)",
        flowers_hint: "Flowers in Car: specify clothing (e.g., black dress)",
        mirror_male_hint: "Mirror Selfie: describe clothes, glasses, phone",
        svoboda_hint: "Free (F): enter prompt",
        svoboda_male_hint: "Free (M): enter prompt",
        flash_title: "DeepSeek V4 Flash",
        flash_desc: "Fast model for code, texts, everyday tasks. Mixture of Experts architecture (236B parameters, 16B active). Context window: 1M tokens, output up to 384K tokens. Supports Reasoner mode. Open MIT license.",
        pro_title: "DeepSeek V4 Pro",
        pro_desc: "Flagship model for complex projects, analysis, large tasks. Mixture of Experts architecture (685B parameters, 37B active). Context window: 1M tokens, output up to 384K tokens. Built-in Reasoner mode. Open MIT license.",
        prompts_title: "Prompt Library",
        prompts_male: "Male AI Photoshoot",
        prompts_female: "Female AI Photoshoot",
        prompts_kids: "Kids Photoshoot (soon)",
        prompts_anime: "Anime Styles (soon)",
        home: "Home",
        female_title: "Female AI Photoshoot",
        female_subtitle: "10 prompts for creating female looks",
        female_intro: "Creating professional female portraits with artificial intelligence has become accessible to everyone — no photographer, studio, or expensive equipment needed. Modern neural networks generate images visually indistinguishable from professional work in minutes. Just upload your photo and specify your desired look through a text instruction — a prompt.",
        male_title: "Male AI Photoshoot",
        male_subtitle: "10 prompts for creating male looks",
        male_intro: "Creating professional male portraits with artificial intelligence has become accessible to everyone — no photographer, studio, or expensive equipment needed. Modern neural networks generate images visually indistinguishable from professional work in minutes. Just upload your photo and specify your desired look through a text instruction — a prompt.",
        copy: "Copy",
        copy_telegram: "Copy to Telegram",
        later: "Coming soon",
        back_prompts: "Back to prompts",
        copied: "Copied",
        choose_model: "Select model",
        fast: "Fast",
        best: "Best",
        storage_title: "Generation Storage",
        loading: "Loading...",
        auth_required: "Please log in on the main page",
        empty_storage: "Nothing here yet",
        loading_prompt: "Loading prompt...",
        no_prompt: "No prompt",
        delete: "Delete",
        confirm_delete: "Delete file?",
        error_loading: "Loading error",
    }
};